name: Exasol in Azure on Ubuntu
description: Provisioning in Azure. Ubuntu, managed disks, static public IP.
backend: tofu

compatibility:
  provides:
    - admin-ui
    - remote-exec

tofu:
  variablesFile: variables_public.tf
  varsOutputFile: vars.tfvars
