name: Exasol in AWS on Ubuntu
description: Provisioning in AWS. Ubuntu, S3 archive volume, dynamic IP.
backend: tofu

compatibility:
  provides:
    - admin-ui
    - remote-exec

tofu:
  variablesFile: variables_public.tf
  varsOutputFile: vars.tfvars
