name: Exasol on Exoscale with Ubuntu
description: Provisioning on Exoscale. Ubuntu, SOS archive volume, public IPs.
backend: tofu

compatibility:
  provides:
    - admin-ui
    - remote-exec

tofu:
  variablesFile: variables_public.tf
  varsOutputFile: vars.tfvars
